### ISSUE TITLE
是否支持ARM设备?

### ISSUE THREAD

**Issue by Ericxiaoshuang** [Har-Kuun/OneClickDesktop#1]
比如树莓派4的ubuntu系统

**Comment by Har-Kuun** [comment]
我手上也没有ARM设备可以用来测试，不过理论上应该是可以的，依赖环境可能需要修改一下。

**Comment by Ericxiaoshuang** [comment]
> 我手上也没有ARM设备可以用来测试，不过理论上应该是可以的，依赖环境可能需要修改一下。

我的树莓派4装了宝塔面板,等有空用新的tf卡测试下
