### ISSUE TITLE
ubuntu 18.04 缺少libpng无法继续安装。

### ISSUE THREAD

**Issue by oxcz** [Har-Kuun/OneClickDesktop#11]
这个我也不知道算不算问题。
checking pngstruct.h usability... no
checking pngstruct.h presence... no
checking for pngstruct.h... no
checking for cos in -lm... yes
checking for png_write_png in -lpng... no
configure: error: "libpng is required for writing png messages"

[31m依赖环境缺失。(B[0m
请核查日志，安装必要的依赖环境，并再次运行此脚本。
欢迎您在https://github.com/Har-Kuun/OneClickDesktop/issues这里提交错误报告，以便我修复脚本。
谢谢！
先提一个Issues了。

**Comment by majianyu2007** [comment]
有个好东西叫百度

**Comment by majianyu2007** [comment]
看看有用吗https://blog.csdn.net/itkbase/article/details/1962125

**Comment by oxcz** [comment]
> 看看有用吗https://blog.csdn.net/itkbase/article/details/1962125

问题是已经解决了。
sudo apt-get install libpng-dev
这样就可以继续安装了。

**Comment by Har-Kuun** [comment]
哎？我的脚本里面明明安装了libpng-dev...为啥还出了问题…楼主用的哪里的镜像？

**Comment by oxcz** [comment]
> 哎？我的脚本里面明明安装了libpng-dev...为啥还出了问题…楼主用的哪里的镜像？

用的就是阿里云的镜像。
