### ISSUE TITLE
ubuntu 18.04 安装vnc-server失败

### ISSUE THREAD

**Issue by oxcz** [Har-Kuun/OneClickDesktop#12]
先把日志贴上来，没有时间继续看了。
`Fetched 146 MB in 16s (9,404 kB/s)
E: Failed to fetch http://mirrors.cloud.aliyuncs.com/ubuntu/pool/main/x/xorg-server/xserver-xorg-core_1.19.6-1ubuntu4.4_amd64.deb  Undetermined Error [IP: 100.100.2.148 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[32m[1m桌面环境，浏览器，以及VNC服务器安装成功。(B[0m
开始配置VNC服务器...

spawn /usr/bin/vncpasswd
couldn't execute "/usr/bin/vncpasswd": no such file or directory
    while executing
"spawn "/usr/bin/vncpasswd""
1.sh: line 288: vncserver: command not found
1.sh: line 290: vncserver: command not found
Job for vncserver@1.service failed because the control process exited with error code.
See "systemctl status vncserver@1.service" and "journalctl -xe" for details.
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver@1.service → /etc/systemd/system/vncserver@.service.
1.sh: line 294: /root/Desktop/EnableCopyPaste.sh: No such file or directory
1.sh: line 293: /usr/bin/vncconfig: No such file or directory
chmod: cannot access '/root/Desktop/EnableCopyPaste.sh': No such file or directory`

**Comment by majianyu2007** [comment]
应该是vnc服务器没有安装。试试apt get update --fix-missing

**Comment by Har-Kuun** [comment]
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing
```
大概率你用的阿里云镜像有问题，apt-get无法获取安装包，可以按楼上说的试试，或者换个源，应该就可以了。
