### ISSUE TITLE
vnc 服务安装失败

### ISSUE THREAD

**Issue by tone0000** [Har-Kuun/OneClickDesktop#14]
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/chou/.vnc/passwd :1 to connect to the VNC server.

Killing Xtigervnc process ID 3355... success!
Warning: The unit file, source configuration file or drop-ins of vncserver@1.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for vncserver@1.service failed because the control process exited with error code.
See "systemctl status vncserver@1.service" and "journalctl -xe" for details.
/usr/bin/vncconfig: unable to open display ":1"

VNC安装失败！

**Comment by Har-Kuun** [comment]
可以加我QQ 694082200把OneClickDesktop.log文件发给我，然后帮你排查。重装一下系统然后使用root用户安装可能可以解决。
