### ISSUE TITLE
阿里云ecs新系统安装也失败了

### ISSUE THREAD

**Issue by oxcz** [Har-Kuun/OneClickDesktop#15]
重新安装的系统，选择的20.04 然后更新了系统。
运行脚本安装。也报错了。
Fetched 109 MB in 37s (2,972 kB/s)
E: Failed to fetch http://mirrors.cloud.aliyuncs.com/ubuntu/pool/universe/e/exo/libexo-1-0_0.12.11-1ubuntu1_amd64.deb  Undetermined Error [IP: 100.100.2.148 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[32m[1mDesktop, browser, and VNC server successfully installed.(B[0m
Starting to configure VNC server...

spawn /usr/bin/vncpasswd
couldn't execute "/usr/bin/vncpasswd": no such file or directory
    while executing
"spawn "/usr/bin/vncpasswd""
1.sh: line 288: vncserver: command not found
1.sh: line 290: vncserver: command not found
Job for vncserver@1.service failed because the control process exited with error code.
See "systemctl status vncserver@1.service" and "journalctl -xe" for details.
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver@1.service → /etc/systemd/system/vncserver@.service.
1.sh: line 294: /root/Desktop/EnableCopyPaste.sh: No such file or directory
1.sh: line 293: /usr/bin/vncconfig: No such file or directory
chmod: cannot access '/root/Desktop/EnableCopyPaste.sh': No such file or directory

[31mVNC installation failed!(B[0m
[33m[1mPlease check the above log for reasons.(B[0m
Please also consider to report your log here https://github.com/Har-Kuun/OneClickDesktop/issues so that I can fix this issue.
Thank you!

**Comment by oxcz** [comment]
运行了apt-get update  --fix-missing
我再试试

**Comment by Har-Kuun** [comment]
阿里云镜像的问题，好多人跟我反映了。换个源可解。
