### ISSUE TITLE
全新纯净Debian10系统安装失败

### ISSUE THREAD

**Issue by gimgoo** [Har-Kuun/OneClickDesktop#16]
如题，多次重复提示缺失依赖：
`2020-08-17 22:31:21 (160 KB/s) - ‘guacamole-server-1.2.0.tar.gz’ saved [1048759/1048759]

Start building Guacamole Server from source...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether make supports nested variables... (cached) no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/guacamole-server-1.2.0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

Missing dependencies.
Please check log, install required dependencies, and run this script again.
Please also consider to report your log here https://github.com/Har-Kuun/OneClickDesktop/issues so that I can fix this issue.
Thank you!`

log中看到有这几个错误：
`E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/f/fcitx/libfcitx-config4_4.2.9.6-5_amd64.deb  Undetermined Error [IP: 124.227.187.244 80]
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/f/fonts-noto/fonts-noto-unhinted_20181227-1_all.deb  Undetermined Error [IP: 124.227.187.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by Har-Kuun** [comment]
阿里云的源有问题，换个源就可以啦。

**Comment by majianyu2007** [comment]
`apt-get install build-essential`
