### ISSUE TITLE
重定向次数太多，无法打开，关闭cloudflare的强制https什么的都没用。

### ISSUE THREAD

**Issue by isyume** [Har-Kuun/OneClickDesktop#17]
重定向次数太多，无法打开，关闭cloudflare的强制https什么的都没用。

**Comment by majianyu2007** [comment]
重装系统，重新安装，先修改代码，将脚本中的`--redirect`全部删除
安装certbot时会让你选择1还是2，自己翻译一下

**Comment by isyume** [comment]
> 重装系统，重新安装，先修改代码，将脚本中的`--redirect`全部删除
> 安装certbot时会让你选择1还是2，自己翻译一下

哈哈，算了，不搞了，脚本不成熟，安装的时候也没有任何提到这个问题的，我看了下之前有issue说这样的问题的，然而还是没改进。哈哈，让其他人用吧，不适合我。

**Comment by majianyu2007** [comment]
> > 重装系统，重新安装，先修改代码，将脚本中的`--redirect`全部删除
> > 安装certbot时会让你选择1还是2，自己翻译一下
> 
> 哈哈，算了，不搞了，脚本不成熟，安装的时候也没有任何提到这个问题的，我看了下之前有issue说这样的问题的，然而还是没改进。哈哈，让其他人用吧，不适合我。

就是我发起的issue
