### ISSUE TITLE
Unable to contact settings server

### ISSUE THREAD

**Issue by 3ruce** [Har-Kuun/OneClickDesktop#19]
I've hit this error on a debian 10 machine on Hetzner in the browser...

```
Unable to contact settings server
/usr/bin/dbus-launch terminated abnormally without any error message
```

![Screenshot_2020-08-24_21-32-05](https://user-images.githubusercontent.com/1258786/91087797-4c982400-e651-11ea-9f32-9cf2b1d85e81.png)

There is a second error message shown...

`Unable to load a failsafe session`

![Screenshot_2020-08-24_21-33-45](https://user-images.githubusercontent.com/1258786/91087952-8e28cf00-e651-11ea-811d-067ee5849e28.png)

I wonder if this is because the Hetzner image is missing something?

**Comment by Har-Kuun** [comment]
Hi, please try `apt-get install dbus-x11 -y` in the terminal then reboot your server.

**Comment by 3ruce** [comment]
Thank you, that worked on Debian 10 and Ubuntu 20.04
