### ISSUE TITLE
支持centos7吗？

### ISSUE THREAD

**Issue by ruix156** [Har-Kuun/OneClickDesktop#2]
支持centos7吗？

**Comment by Har-Kuun** [comment]
暂时不支持，过几天会增加CentOS 8的支持。CentOS 7上面各版本的程序都太老旧了，如果要适配的话基本上脚本要重新写，而且只能装旧版本的各软件包，因此如果需求量大的话我再考虑添加。一般来说，这个程序不适合与其他程序共存，因此这里建议直接重装一个Ubuntu或者Debian, 比较方便。

**Comment by Har-Kuun** [comment]
已支持CentOS 7/8.
