### ISSUE TITLE
安装完成后访问域名打开是nginx的欢迎使用页面

### ISSUE THREAD

**Issue by MiriaPan** [Har-Kuun/OneClickDesktop#21]
环境 :ubuntu 18.04
安装过程顺利完成（没有安装ssl 所以选择了N）
安装完成后没有错误报错。但打开域名，提示的是Ningx默认安装完成后的欢迎使用页面，没有看到桌面！

**Comment by Har-Kuun** [comment]
访问http://example.com:8080/guacamole能看到桌面吗
