### ISSUE TITLE
Tomcat Centos下载源404

### ISSUE THREAD

**Issue by majianyu2007** [Har-Kuun/OneClickDesktop#24]
Tomcat Centos下载源404
原命令
[https://github.com/Har-Kuun/OneClickDesktop/blob/master/OneClickDesktop_zh-CN.sh#L345](https://github.com/Har-Kuun/OneClickDesktop/blob/master/OneClickDesktop_zh-CN.sh#L345)
`curl -s https://mirrors.ocf.berkeley.edu/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz`
其中
[https://mirrors.ocf.berkeley.edu/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz](https://mirrors.ocf.berkeley.edu/apache/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz)
404了，tomcat目录只有9.0.41和9.0.43版本的。

**Comment by Har-Kuun** [comment]
Thank you.  Fixed.
