### ISSUE TITLE
Script installed ok but the XFCE desktop had no audio

### ISSUE THREAD

**Issue by bmullan** [Har-Kuun/OneClickDesktop#28]
When I ran the install script I **selected to use RDP**.

After install I could log into the XFCE desktop ok.

I attempted to use the Browser to play a Youtube Music Video

The Youtube Music video would play ok **_but there was no audio_**.

**pavucontrol** only showed "dummy" devices where I would have expected to xrdp-pulseaudio,,,,,,

Here is a site that develops install scripts for XRDP which enables Audio/Pulseaudio

**https://c-nergy.be/blog/?p=16817**

** NOTE ** the section on the above web page that talks about....

> Standard Installation with Parameters
> 
> The script can be used to perform a standard installation and still passes some parameters to get the most of the xRDP packages and their features.  For all the Ubuntu versions, we could use the following combination of parameters 
> 
>     **./xrdp-installer-1.2.3.sh -s      (this would enable the sound redirection)** 
>     ./xrdp-installer-1.2.3.sh -l      (this would customize the xrdp login screen -see here)
> 
> Obviously, you can combine the switches (any order) to have more features enabled  
> 
>     ./xrdp-installer-1.2.3.sh -s -l      (this would enable the sound redirection and customizing the login screen)

**Comment by Har-Kuun** [comment]
Thanks, I'll look into that.

**Comment by bmullan** [comment]
I would also look into giving the installer a choice of Desktops ... Mate and XFCE would be two good choices.

I personnaly like Mate :-)

**Comment by bmullan** [comment]
@Har-Kuun 

FYI... I was happy to find someone else that implemented a Bash install for guacamole, nginx, mysql, tomcat9

My github repo is here:  **[CIAB Remote Desktop system](https://github.com/bmullan/ciab-remote-desktop)**

There must have been some recent upstream changes I'm still tracking down my CIAB installs but you can't connect to 
it right now.   But that was when I was attempting to upgrade CIAB for use with Ubuntu 20.04 LTS instead of 18.04.

I'm writing this because I extensively commented the Bash scripts and you may find some useful snippets of code in
there to help you with your OneClickDesktop code.

For instance for the Guacamole users to hear audio on their Desktop you will note sections of code in the
 mk-cn1-environment.sh_  script 

- such as a section about install/config of Mate, XFCE (xubuntu desktop) or Budgie.   All 3 of those are Desktops are light weight.

> echo "Installing Ubuntu-MATE desktop environment as default for Guacamole RDP User to work with."
> echo
> echo "you can change this to xfce4 (ie xubuntu) by changing just 2 lines of code in the mk-cn1-environment.sh script."
> 
> sudo apt-get install lightdm ubuntu-mate-core ubuntu-mate-desktop -y
> 
> echo
> echo
> echo "Desktop Install Done"
> echo
> echo "Configuring the Xsession file default desktop environment to make ALL future Users default xsession to be UBUNTU-MATE..." 
> echo
> echo
> 
> sudo update-alternatives --set x-session-manager /usr/bin/mate-session
> 
> #===================================================================================================
> # Note:  if you wanted to use XFCE4 desktop (ie xubuntu desktop) instead of MATE you would use the following 
> #        lines instead of the above.
> #====================================================================================================
> 
> # sudo apt-get install lightdm xubuntu-desktop -y
> # sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
> 
> #====================================================================================================
> # Note:  if you wanted to use the Budgie desktop instead of MATE you would use the following 
> #        line instead of the above.
> #==================================================================================================
> 
> # sudo apt-get install lightdm ubuntu-budgie-desktop -y
> 
> #-----------------------------------------------------------------------------------------------------------
> #        For the Budgie Desktop Session to launch correctly with an XRDP conection you will also be required
> #        to make a small edit of the /etc/xrdp/sesman.ini file.  
> #
> #        Comment out the last 2 lines of /etc/xrdp/sesman.ini and add the budgie-desktop line as follows:
> #
> #        # test -x /etc/X11/Xsession && exec /etc/X11/Xsession
> #        # exec /bin/sh /etc/X11/Xsession
> #        budgie-desktop
> 

and this snippet of Bash script to configure the system so all future users added to the desktop get audio

> #====================================================================================================
> # in order for all new users added to this server via sudo adduser xxx in the future we need to change the /etc/adduser.conf file
> # to set /etc/adduser.conf to add all new users accounts created to the audio/pulse/pulse-access groups
> #
> # To do this we need to change the following 2 lines in adduser.conf.
> #
> # The following line needs to be first be uncommented & also changed to "include" the groups we want the user added to
> ##EXTRA_GROUPS="dialout cdrom floppy audio video plugdev users"
> # and 
> # The following line just needs to be uncommented so the EXTRA_GROUPS option above will be default behavior for adding new, non-system users
> ##ADD_EXTRA_GROUPS=1
> #
> # make the 1st change
> sudo sed -i 's/#EXTRA_GROUPS="dialout cdrom floppy audio video plugdev users"/EXTRA_GROUPS="audio pulse pulse-access"/' /etc/adduser.conf
> # make the 2nd change
> sudo sed -i 's/#ADD_EXTRA_GROUPS=1/ADD_EXTRA_GROUPS=1/' /etc/adduser.conf

Hope some of this helps get your audio working for users of your OneClickDesktop!

If I can help in  any way let me know.   I've got time while I try to figure out my own problem w/CIAB.

Brian

**Comment by bmullan** [comment]
@Har-Kuun 

By the way... good job on your OneClickDesktop work... !

**Comment by Har-Kuun** [comment]
Audio function has now been added.
https://github.com/Har-Kuun/OneClickDesktop/tree/master/plugins/Audio
Thanks again for the help.
