### ISSUE TITLE
Installation of a self-signed certificate instead of Let's Encrypt

### ISSUE THREAD

**Issue by bmullan** [Har-Kuun/OneClickDesktop#29]
see title.

It can be valuable for Guacamole remote desktop  installs to offer Installer choice of using LetsEncrypt Cert or just a Self-Signed Cert.

For testing or just internal use only... a Self-Signed Cert works fine.   Later the Installer could change to a LetsEncrypt Cert 

Brian

**Comment by bmullan** [comment]
I got the self-signed cert to work with your OneClickDesktop script.

Here's what I did...

Ran **OneClickDesktop.sh** 
note: Answer NO to installing NGINX

When your script is done...

Executed: **wget https://github.com/bmullan/ciab-remote-desktop/blob/master/setup-nginx.sh** 
to retrieve my **setup-nginx.sh** script from my [CIAB Remote Desktop github ](https://github.com/bmullan/ciab-remote-desktop)

then Ran **setup-nginx.sh**

When it was done I could use HTTPS via the self-signed cert created by setup-nginx.sh to access Guacamole installed by your script.

See if it works for you and let me know.

**Comment by Har-Kuun** [comment]
Thanks for providing this tutorial.  This is not a very common request, so I'm not adding it now in the script, but people who do wish to install a self-signed cert will be able to follow your comment above.
