### ISSUE TITLE
支持ipv6吗

### ISSUE THREAD

**Issue by majianyu2007** [Har-Kuun/OneClickDesktop#3]
rt
还有一个问题：域名是ssh连接到的域名还是hostname？

**Comment by Har-Kuun** [comment]
支持IPv6, 这个脚本在前面安装了Nginx反代，因此Nginx支持的特性都能够支持。
域名是任意的，只需要随便解析一个子域名/免费域名到服务器的IP地址上即可，无需是服务器的hostname或者用来连接SSH的域名.

**Comment by majianyu2007** [comment]
那直接访问就521 Web server is down
现在在重装

**Comment by Har-Kuun** [comment]
安装的时候有报错吗？

**Comment by majianyu2007** [comment]
没有

**Comment by Har-Kuun** [comment]
访问一下服务器IP:8080能不能打开呢？

**Comment by majianyu2007** [comment]
过会我重装，再试试。默认端口是8080吗？

**Comment by Har-Kuun** [comment]
tomcat监听8080，前端nginx反代，监听80和443. 用IP地址:端口号可以判断这两个服务器程序是否正常运行。
如果你的域名正常解析到这个IP, 然后程序安装的时候设置了这个域名，应该是不会有问题的。

**Comment by majianyu2007** [comment]
待会我试试再来回复，谢谢了

**Comment by majianyu2007** [comment]
![E9DDA3AD-1654-4AF6-B34A-E0F37DD3C808](https://user-images.githubusercontent.com/61257641/89164740-0c8dd600-d5aa-11ea-80df-da609c92ad42.png)
成功，套上cf再试试

**Comment by majianyu2007** [comment]
guacamole怎么更改密码，密码中有@（应该是这个原因），提示非法登录

**Comment by majianyu2007** [comment]
翻脚本改了，挺好用的，就是有些慢，个人问题
