### ISSUE TITLE
Is adding a mysql/mariadb to OneClickDesktop a thought yet

### ISSUE THREAD

**Issue by bmullan** [Har-Kuun/OneClickDesktop#30]
I just realized/noticed that OneClickDesktop  doesn't provide way to utilize the guacamole admin web service to add new users, connections only view active connections and be able to "kill" them?

https://guacamole.apache.org/doc/gug/administration.html

Any thought to adding the mysql/mariadb & configuration to use Guacamole's advanced Admin capabilities?

thanks

**Comment by Har-Kuun** [comment]
You can add new users, add new connections, etc., by editing /etc/guacamole/user-mapping.xml file.

This script was meant to provide a quick, easy, and simple solution for linux desktop with browser access; with that in mind, it's a bit redundant to implement DB-based configurations for Guacamole.

**Comment by bmullan** [comment]
@Har-Kuun 
Thanks.. I understand this would be a different use case that what you intended.

And yes I know users could manually edit user-mapping.xml **but** what if a user wanted to support hundreds of users and hundreds of "connections" ?    

Anyway thanks for replying.
