### ISSUE TITLE
mirrors.ocf.berkeley.edu Connection refused

### ISSUE THREAD

**Issue by Jakob-Boy** [Har-Kuun/OneClickDesktop#31]
`--2021-09-27 01:24:56--  https://mirrors.ocf.berkeley.edu/apache/guacamole/1.2.0/source/guacamole-server-1.2.0.tar.gz
Resolving mirrors.ocf.berkeley.edu (mirrors.ocf.berkeley.edu)... 169.229.226.30, 2607:f140:8801::1:30
Connecting to mirrors.ocf.berkeley.edu (mirrors.ocf.berkeley.edu)|169.229.226.30|:443... failed: Connection refused.
Connecting to mirrors.ocf.berkeley.edu (mirrors.ocf.berkeley.edu)|2607:f140:8801::1:30|:443... failed: Network is unreachable.
tar (child): guacamole-server-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
OneClickDesktop_zh-CN.sh: line 239: cd: /root/guacamole-server-1.2.0: No such file or directory
开始安装Guacamole服务器...
OneClickDesktop_zh-CN.sh: line 241: ./configure: No such file or directory

依赖环境缺失。`

**Comment by Jakob-Boy** [comment]
debian10的系统

**Comment by Har-Kuun** [comment]
感谢提醒。目前Berkeley镜像站宕机了，请将安装脚本中的这个链接 https://mirrors.ocf.berkeley.edu/apache/guacamole/1.2.0/source/guacamole-server-1.2.0.tar.gz 替换为 https://downloads.apache.org/guacamole/1.2.0/source/guacamole-server-1.2.0.tar.gz 应该就可以用了。
我明天会再检查一下这个镜像站是否还可以使用，如果依然宕机的话我会直接修改脚本了。
