### ISSUE TITLE
连接出错

### ISSUE THREAD

**Issue by weixiabing** [Har-Kuun/OneClickDesktop#32]
![屏幕截图 2021-12-08 225450](https://user-images.githubusercontent.com/13848491/145229910-482cea3f-9009-4ad2-9177-3f7ebf08402c.png)
如图
原来的log被覆盖了
大概是这个问题：
X connection to localhost:1host broken (explicit kill or server shutdown)
有大佬帮我解决一下吗

**Comment by Har-Kuun** [comment]
运行一下```ss -lntp | grep xrdp```，看看什么情况。可以加我QQ 694082200具体问
