### ISSUE TITLE
AudioRedirectionSetup

### ISSUE THREAD

**Issue by yuskang** [Har-Kuun/OneClickDesktop#33]
您好，我在執行腳本AudioRedirectionSetup.sh時，發生如log文檔錯誤，是否是因為pulseaudio版次更新了而無法對應這個腳本？
[OneClickDesktop_AudioRedirection.log](https://github.com/Har-Kuun/OneClickDesktop/files/7696284/OneClickDesktop_AudioRedirection.log)

**Comment by Har-Kuun** [comment]
感觉可能是的。可以把脚本第185行···pulsever=$(pulseaudio --version | awk '{print $2}')···改成对应的版本号，应该就可以了。

**Comment by yuskang** [comment]
大大，不好意思，語法不太熟悉，該怎麼修改呀？

**Comment by Har-Kuun** [comment]
加我QQ吧，694082200
