### ISSUE TITLE
guacamole连接失败，声音也配置失败

### ISSUE THREAD

**Issue by Colo-Thor** [Har-Kuun/OneClickDesktop#35]
![捕获](https://user-images.githubusercontent.com/80299243/160286379-cb76bc41-2254-477c-a2db-4917547db483.PNG)

![捕获1](https://user-images.githubusercontent.com/80299243/160286443-02881962-a589-4c1e-a803-0c43142b9fe1.PNG)
![捕获2](https://user-images.githubusercontent.com/80299243/160286466-01576657-0fbb-48ef-a69e-264f6b09d35d.PNG)
[OneClickDesktop_AudioRedirection.log](https://github.com/Har-Kuun/OneClickDesktop/files/8357850/OneClickDesktop_AudioRedirection.log)

**Comment by Har-Kuun** [comment]
Guacamole在系统重启后要过5-10分钟左右才能连上，可能是这个原因。
pulseaudio是不能用root用户运行的，否则就会报这样的错误，需要用非root账户在桌面上的终端里面执行。
