### ISSUE TITLE
XRDP安装失败!

### ISSUE THREAD

**Issue by pubshare2** [Har-Kuun/OneClickDesktop#38]
大佬请看一下以下报错，谢谢。

编译条件已满足！
开始编译源码...

make  all-recursive
make[1]: Entering directory `/home/opc/xrdp'
Making all in common
make[2]: Entering directory `/home/opc/xrdp/common'
  CC       base64.lo
  CC       fifo.lo
  CC       file.lo
  CC       guid.lo
guid.c: In function 'guid_new':
guid.c:36:12: error: missing braces around initializer [-Werror=missing-braces]
     struct guid guid = {0};
            ^
guid.c:36:12: error: (near initialization for 'guid.g') [-Werror=missing-braces]
cc1: all warnings being treated as errors
make[2]: *** [guid.lo] Error 1
make[2]: Leaving directory `/home/opc/xrdp/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/opc/xrdp'
make: *** [all] Error 2
Making install in common
make[1]: Entering directory `/home/opc/xrdp/common'
  CC       guid.lo
guid.c: In function 'guid_new':
guid.c:36:12: error: missing braces around initializer [-Werror=missing-braces]
     struct guid guid = {0};
            ^
guid.c:36:12: error: (near initialization for 'guid.g') [-Werror=missing-braces]
cc1: all warnings being treated as errors
make[1]: *** [guid.lo] Error 1
make[1]: Leaving directory `/home/opc/xrdp/common'
make: *** [install-recursive] Error 1
Failed to start xrdp.service: Unit not found.

XRDP安装失败!
请检查上面的日志。

**Comment by Har-Kuun** [comment]
你好，请问是否是CentOS 7操作系统？CentOS系列操作系统今年起已经失去了官方支持，导致部分程序异常。
从你描述的问题看，这里是CentOS部分系统中编译器的问题。如果您想继续在CentOS 7上面安装，需要手动将guid.c文件的第36行
```struct guid guid = {0};```
改成
```struct guid guid = {{0}};```
然后重新编译应该就可以了。当然，更好的办法是使用Debian/Ubuntu系列操作系统。

参考：https://github.com/neutrinolabs/xrdp/pull/2011#commitcomment-63453607
