### ISSUE TITLE
重定向次数过多

### ISSUE THREAD

**Issue by majianyu2007** [Har-Kuun/OneClickDesktop#6]
桌面没有顶上那个栏，于是想重启一次，重启完就重定向次数过多。

**Comment by majianyu2007** [comment]
解决方案：关闭cloudflare的https重写
或着：
重新安装，执行脚本前把所有的--redirect全删除，安装到最后会让你选择，选择noredirect（应该是1）即可

**Comment by Har-Kuun** [comment]
👍
