### ISSUE TITLE
nginx变为可选安装

### ISSUE THREAD

**Issue by zlj88** [Har-Kuun/OneClickDesktop#9]
建议把nginx反代变为可选项，可以通过ip:8080/guacamole访问，同时建议增加修改8080为其它端口的功能。

**Comment by majianyu2007** [comment]
可以自己修改脚本

**Comment by Har-Kuun** [comment]
好的，后续会考虑增加此功能，目前如果不需要nginx反代，可以按照楼上说的，手动修改一下脚本哈，把`main`函数里面`install_reverse_proxy`这行注释掉即可。

**Comment by Har-Kuun** [comment]
This feature is now included in v0.1.0.
